Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("login.urls")),
    path("", include("dashboard.urls")),
    path("", include("notice_board.urls")),
    path("", include("enroll.urls")),
]

dashboard/urls.py
from django.urls import include, path
from .views import (add_assignment_view, check_off_assignment, delete_completed_assignment, user_schedule_view, CourseDetailView, CourseIndexView, add_course, upload_course_file,
                    upload_course_image, user_schedule_view_complete, view_course_file, delete_course_file,
                    course_file_search, delete_course)

urlpatterns = [
    path('assignments/', user_schedule_view, name='schedule_view'),
    path('assignments/complete', user_schedule_view_complete, name='user_schedule_complete'),
    path('assignments/complete/delete/<int:assignment_id>', delete_completed_assignment, name='delete_completed'),
    path('assignments/submit/<int:assignment_id>', check_off_assignment, name='turn_in'),
    path('course/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('course/<int:course_id>/delete', delete_course, name='course_delete'),
    path('course/<int:course_id>/add', add_assignment_view, name='course_assignment_add'),
    path('course/', CourseIndexView.as_view(), name='course_index'),
    path('course/add', add_course, name='course_add'),
    path('course/<int:course_id>/upload/', upload_course_file, name='upload_course_file'),
    path('course/<int:course_id>/upload_image/', upload_course_image, name='upload_course_image'),
    path('files/<int:file_id>/', view_course_file, name='view_course_file'),
    path('course-file/delete/<int:file_id>/', delete_course_file, name='delete_course_file'),
    path('course/<int:course_id>/course_file_search/', course_file_search, name='search_course_file'),
    path("", include("login.urls")),
]

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.login_page, name="login_page"),
    path("logout", views.logout_view, name="logout"),
    path("guest_login", views.guest_login, name="guest_login"),
    path("admin_user_page", views.admin_user_page, name="admin_user_page"),
    path("normal_user_page", views.normal_user_page, name="normal_user_page"),
    path("guest_page", views.guest_page, name="guest_page"),
    path("profile", views.profile, name="profile"),
]

dashboard/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.core.files.storage import default_storage
from io import BytesIO
from django.core.files.base import ContentFile


class Course(models.Model):
    objects = None
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    instructor = models.CharField(max_length=200)
    description = models.TextField()
    course_image = models.ImageField(default='default.jpg', upload_to='course_pics')
    # schedules = models.ManyToManyField(Schedule)

    def __str__(self):
        # return f"{self.name} \n {self.instructor} \n {self.description}"
        return f"{self.name}"

    # Adjust image size
    def save(self,*args, **kwargs):
        if self.pk:
            old_course = Course.objects.get(pk=self.pk)
            old_image = old_course.course_image
            # Ensure it's not the default image and that the name has changed
            if old_image.name != self.course_image.name and old_image.name != 'default.jpg':
                old_image.delete(save=False)  # Delete the old image from S3

        super().save(*args, **kwargs)

        with default_storage.open(self.course_image.name, 'rb') as storage:
            img = Image.open(storage)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size, Image.Resampling.LANCZOS)

                in_memory_file = BytesIO()
                img_format = img.format if img.format is not None else 'JPEG'
                img.save(in_memory_file, format=img_format)
                in_memory_file.seek(0)

                # Ensure the image is saved back to storage
                self.course_image.save(self.course_image.name, ContentFile(in_memory_file.getvalue()), save=True)

                # It's important to clear the buffer after use
                in_memory_file.close()


class CourseFile(models.Model):
    FILE_TYPE_CHOICES = [
        ('txt', 'Text File'),
        ('pdf', 'PDF File'),
        ('jpg', 'JPG File')
    ]

    CONTENT_TYPE_CHOICES = [
        ('OTH', 'Other'),
        ('SYL', 'Syllabus'),
        ('SLD', 'Slides'),
        ('PAP', 'Past Paper'),
        ('SOL', 'Exam Solution'),
        ('HWK', 'Homework'),
    ]

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='files')
    keywords = models.CharField(max_length=255, help_text="Enter keywords separated by commas.", null = True)
    file_type = models.CharField(max_length=3, choices=FILE_TYPE_CHOICES)
    content_type = models.CharField(max_length=3, choices=CONTENT_TYPE_CHOICES, null = True)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='course-files/')
    filename = models.CharField(max_length=255, null=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    upload_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.get_file_type_display()} for {self.course.name}"

    def get_keywords_list(self):
        return self.keywords.split(',')


class Assignment(models.Model):
    ASSIGNMENT_TYPES = [
        ("HW", "HOMEWORK"),
        ("EX", "EXAM"),
        ("PRJ", "PROJECT"),
        ("Q", "QUIZ"),
    ]

    course_name = models.ForeignKey(Course, on_delete=models.CASCADE, null=True) #
    # course_name = models.CharField(max_length=100)
    description = models.TextField()
    assignment_type = models.CharField(max_length=20, choices=ASSIGNMENT_TYPES)
    priority = models.IntegerField(default=0)  # Set a default value for priority
    link = models.URLField(null=True, blank=True)
    due_date = models.DateField(null=True)
    keywords = models.CharField(max_length=40, blank=True, null=True) #Implmenting this
    date_submitted = models.DateTimeField(default=None)  # New field
    # schedules = models.ManyToManyField(Schedule)                  # Not sure if will need
    # course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.course_name}: \n {self.description} \n {self.assignment_type} \n {self.priority} \n {self.due_date}\n {self.keywords}"

    def set_course_name(self, course_name):
        self.course_name = course_name
        self.save()

    def set_description(self, description):
        self.description = description
        self.save()

    def set_course_code(self, course_code):
        self.course_code = course_code
        self.save()

    def set_assignment_type(self, assignment_type):
        self.assignment_type = assignment_type
        self.save()

    def set_priority(self, priority):
        self.priority = priority
        self.save()

    def set_link(self, link):
        self.link = link
        self.save()

    def set_due_date(self, due_date):
        self.due_date = due_date
        self.save()

    def is_due_soon(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.due_date <= now

    def set_keywords(self, keywords):
        self.keywords = keywords.split(',')
        self.save()


class UserSchedule(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    assignments = models.ManyToManyField(Assignment, related_name='user_schedules')
    completed_assignments = models.ManyToManyField(Assignment, related_name='user_schedules_complete')
    
    def __str__(self):
        return f"{self.user.username}'s Schedule"

dashboard/forms.py
from django import forms
from dashboard.models import Assignment, Course
from .models import CourseFile


class AddCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name','instructor','description']


class AddAssignmentToCourseForm(forms.ModelForm):
    due_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))  # Updated field

    class Meta:
        model = Assignment
        fields = ['description', 'assignment_type', 'due_date', 'priority', 'keywords']


class CourseFileForm(forms.ModelForm):
    class Meta:
        model = CourseFile
        fields = ['file', 'filename', 'content_type', 'keywords', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'placeholder': 'Enter the description for this material'}),
        }

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if file:
            file_type = file.name.split('.')[-1].lower()
            if file_type not in ['txt', 'pdf', 'jpg']:
                raise forms.ValidationError("Unsupported file type.")
        return file


class FilterCourseFiles(forms.ModelForm):
    class Meta:
        model = CourseFile
        fields = ['filename', 'content_type', 'keywords']

    def __init__(self, *args, **kwargs):
        super(FilterCourseFiles, self).__init__(*args, **kwargs)
        self.fields['filename'].required = False
        self.fields['content_type'].required = False
        self.fields['keywords'].required = False

dashboard/templates/dashboard/add_course.html
{% extends 'login/base.html' %}
{% block content %}
<div class="container mt-4  mb-4">
    <div>
        <div class="mb-4">
            <h1 class = "text-center">Create a new project</h1>
        </div>


        <form action="{% url 'course_add' %}" method="post" class="form">
            {% csrf_token %}

            <div class="mb-3">
                <table class="table table-borderless">
                    {{ form.as_table }}
                </table>
            </div>

            <div class="text-center">
                <input type="submit" value="Submit" class="btn btn-primary"/>
            </div>
        </form>

    </div>
</div>
{% endblock content %}

dashboard/templates/dashboard/course_assignment_add.html
    <h1>Add a Task to {{ course }}</h1>

    <form action="{% url 'course_assignment_add' course_id%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ Aform }}

        <input type="submit" value="Submit">
    </form>

dashboard/templates/dashboard/course_assignment_files.html
{% extends 'login/base.html' %}
{% block content %}
<div class="container mt-3">
    <h1>Course: {{ course.name }} Assignment Files</h1>
    <h2>Filter Assignment Files</h2>
    <form action="{% url 'get_course_assignment_files' course.id%}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Filter" />
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>File</th>
                <th>Category</th>
                <th>Time Uploaded</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for file in files %}
            <tr>
                <td><a href="{% url 'view_assignment_file' file.id %}">{{ file.file_name }}</a></td>
                <td>{{file.file_category}}</td> 
                <td>{{file.upload_time}}</td>
                <td>{{file.file_description}}</td>          
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">No Files Found</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

dashboard/templates/dashboard/course_detail.html
{% extends 'login/base.html' %}
{% block content %}
<div class="container mt-4  mb-4">

    <div class="row align-items-center">
        <div class="col-md-6">
            <h1>{{ object.name }}</h1>
            <h4>{{ object.instructor }}</h4>
            <p>{{ object.description }}</p>
        </div>

        <div class="col-md-6 text-center">
            <img src="{{ object.course_image.url }}" class="img-fluid" alt="Course Image">

            <div class="my-3">
                <form action="{% url 'upload_course_image' object.id %}" method="post" enctype="multipart/form-data"
                      class="form-inline">
                    {% csrf_token %}
                    <div class="form-group row align-items-center">
                        <div class="col-auto">
                            <input type="file" id="image-upload" name="image" accept="image/*" class="form-control"
                                   required>
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-outline-secondary">Upload Image</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
        <div class="my-3">
            <a href="{% url 'list-messages' object.id %}" class="btn btn-primary">Project Forum</a>
        </div>
    </div>


    <h4>Project Files:</h4>
    <form method="get" action="{% url 'course_detail' object.id %}" class="mb-3">
        <div class="input-group">
            <input type="text" name="file_search" class="form-control" placeholder="Search by keyword"
                   value="{{ file_search_term }}">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </form>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Filename</th>
            <th>Content Type</th>
            <th>Uploaded By</th>
            <th>Upload Date</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for file in course_files %}
        <tr>
            <td>{{ file.filename }}</td>
            <td>{{ file.get_content_type_display }}</td>
            <td>{{ file.uploaded_by }}</td>
            <td>{{ file.upload_date }}</td>
            <td>
                <a href="{% url 'view_course_file' file.id %}">View</a>
                {% if request.user == file.uploaded_by or pma_admin %}
                    <a href="{% url 'delete_course_file' file.id %}"
                    onclick="return confirm('Are you sure you want to delete this file?');">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No files uploaded for this project.</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="row align-items-start">
        <div class="col-md-6 center">
            <a href="{% url 'upload_course_file' object.id %}" class="btn btn-primary">Upload Project File</a>
        </div>
    </div>
    <div class="mt-4">
        <h4>Tasks:</h4>
    </div>
    <form method="get" action="{% url 'course_detail' object.id %}" class="mb-3">
        <div class="input-group">
            <input type="text" name="search" class="form-control" placeholder="Search by keyword"
                   value="{{ search_term }}">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </form>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Type</th>
            <th>Description</th>
            <th>Due Date</th>
            <th>Priority</th>
            <th>Date Submitted</th> <!-- New column for submission time -->

        </tr>
        </thead>
        <tbody>
        {% for assignment in assignments %}
        <tr>
            <td>{{ assignment.assignment_type }}</td>
            <td>{{ assignment.description }}</td>
            <td>{{ assignment.due_date }}</td>
            <td>{{ assignment.priority }}</td>
            <td>{{ assignment.date_submitted }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No tasks available.</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row align-items-center">
        <div class="col-md-6 text-start">
            <a href="{% url 'course_assignment_add' object.id%}" class="btn btn-primary">Add Task to the Project</a>
        </div>
    </div>
</div>

{% endblock content %}

dashboard/templates/dashboard/course_file_search.html
{% extends 'login/base.html' %}
{% block content %}

<h1>Files for Course: {{ course.name }}</h1>

    <form method="post" action="{% url 'search_course_file' course.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Search</button>
    </form>

  <h4>Course Files:</h4>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Filename</th>
            <th>Content Type</th>
            <th>Uploaded By</th>
            <th>Upload Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for file in files %}
        <tr>
            <td>{{ file.filename }}</td>
            <td>{{ file.get_content_type_display }}</td>
            <td>{{ file.uploaded_by }}</td>
            <td>{{ file.upload_date }}</td>
            <td>
                <a href="{% url 'view_course_file' file.id %}">View</a>
                <a href="{% url 'delete_course_file' file.id %}" onclick="return confirm('Are you sure you want to delete this file?');">Delete</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No files available for this course.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mt-3">
    <a href="{% url 'course_detail' course.id %}" class="btn btn-secondary">Back to Course</a>
</div>

{% endblock content %}

dashboard/templates/dashboard/course_index.html
{% extends 'login/base.html' %}
{% block content %}

<div class="container mt-4 mb-4">
    <h1 class="mb-4 text-center">Projects</h1>

    <div class="row">
        {% if course_list %}
            {% for course in course_list %}
                <!-- Course Card -->
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title text-center fw-bold">{{ course.name }}</h5>
                            <p class="card-text">
                                {{ course.instructor }}<br>
                                {{ course.description|truncatewords:20 }}
                            </p>
                            {% if username_startswith_guest %}
                            <p>login to check course detail</p>
                            {% else %}
                            <a href="{% url 'course_detail' course.id %}" class="btn btn-outline-primary">VIEW </a>
                                {% if request.user == course.owner or pma_admin %}
                                <a href="{% url 'course_delete' course.id %}"
                                   onclick="return confirm('Are you sure you want to delete this course?');"
                                   class="btn btn-outline-primary">DELETE </a>
                                {% else %}
                                <a href="{% url 'enroll' course.id %}" class="btn btn-outline-primary">JOIN </a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-3">No courses are available.</p>
        {% endif %}
    </div>

    <!-- Add Course Button -->
    <div class="text-center mt-3">
        <a href="{% url 'course_add' %}" class="btn btn-primary">Add Course</a>
    </div>
</div>

{% endblock content %}

dashboard/templates/dashboard/upload_course_file.html
{% extends 'login/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-3">
    <form action="{% url 'upload_course_file' course.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Upload file to {{ course.name }}</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Upload</button>
        </div>
    </form>

    <div class="mt-3">
        <a href="{% url 'course_detail' course.id %}" class="btn btn-secondary">Back to Course</a>
    </div>
</div>

{% endblock content %}